pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/pps13030596/calculadora', branch: "main"
            }
        }
        stage('Unit Test') {
            steps {
                sh 'python -m unittest discover -s . -p "test_*.py"'
            }
        }
    }
}

